import type { Metadata } from "next";
import { SidebarProvider, SidebarTrigger } from '@/components/ui/sidebar';
import localFont from "next/font/local";
import "./globals.css";
import { AppSidebar } from "@/components/shared/AppSidebar";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable}`}
      >
        <SidebarProvider>
          <AppSidebar />
          <div className="flex flex-col grow">
            <SidebarTrigger />
            <div className="flex p-4 mt-12">
              {children}
            </div>
          </div>
        </SidebarProvider>
      </body>
    </html>
  );
}
